config/routes.rb
Rails.application.routes.draw do
  root 'statements#display'
  get 'statements/display' => 'statements#display'
  get 'statements/deposit_new' => 'statements#deposit_new'
  post 'statements/deposit_new' => 'statements#deposit_create'
  get 'statements/withdrawal_new' => 'statements#withdrawal_new'
  post 'statements/withdrawal_new' => 'statements#withdrawal_create'
  resources :statements

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/statement.rb
class Statement < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
  end

  def deposit_new
    @account = Account.new
  end

  def deposit_create
    @account = Account.new(account_params)
    if @account.save
      flash[:notice] = "You have deposit money"
      redirect_to account_path(@account)
    else
      flash[:notice] = "Your deposit has not gone through, you left something blank."
      render :action=>'deposit_new'
    end
  end

  private

  def account_params
    params.require(:account).permit(:deposit, :withdrawal)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController

  def display
  end

  def index
    @statements = Statement.all
  end

  def deposit_new
    @statement = Statement.new
  end

  def deposit_create
    @statement = Statement.new(statement_params)
    return @statement.balance = statement_params[:deposit] if Statement.sum(:balance).nil?
    calculate_balance(:deposit)

    if !statement_params[:deposit].empty?
      @statement.save
      flash[:notice] = "You have deposit money"
      redirect_to root_path
    else
      flash[:notice] = "Your deposit has not gone through, you left something blank."
      render :action=>'deposit_new'
    end
  end

  def withdrawal_new
    @statement = Statement.new
  end

  def withdrawal_create
    @statement = Statement.new(statement_params)
    calculate_balance(:withdrawal)
    if !statement_params[:withdrawal].empty?
      @statement.save
      flash[:notice] = "You have withdrawal money"
      redirect_to root_path
    else
      flash[:notice] = "Your withdrawal has not gone through, you left something blank."
      render :action=>'deposit_new'
    end
  end

  private

  def calculate_balance(money_exchange)
    @statement.balance = -statement_params[money_exchange].to_f + Statement.sum(:deposit) + (-Statement.sum(:withdrawal))
  end

  def statement_params
    params.require(:statement).permit(:deposit, :withdrawal)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def alert_for(flash_type)
    {
        :success => 'alert-success',
        :error => 'alert-danger',
        :alert => 'alert-warning',
        :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BankTechTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/statements/deposit_new.html.erb
<%= simple_form_for @statement, :url => statements_deposit_new_path, :method => :post do |f| %>
  <%= f.number_field :deposit %>
  <%= f.button :submit, "Submit", class: 'btn-success btn-block' %>
<% end %>

app/views/statements/display.html.erb
<ul>
  <li> <a href="/statements/deposit_new">Deposit Money</a> </li>
  <li> <a href="/statements/withdrawal_new">Withdrawal Money</a> </li>
  <li> <a href="/statements">Bank Statement</a> </li>
</ul>

app/views/statements/index.html.erb
<% if @statements.any? %>
  <% @statements.each do |statement| %>
    <ul>
    <li>Created At: <%= statement.created_at %></li>
    <li>Credit: <%= statement.deposit %></li>
    <li>Debit: <%= statement.withdrawal %></li>
    <li>Balance: <%= statement.balance %></li>
  </ul>
  <% end %>
<% else %>
  <h1>No Bank Statements yet</h1>
<% end %>

app/views/statements/withdrawal_new.html.erb
<%= simple_form_for @statement, :url => statements_withdrawal_new_path, :method => :post do |f| %>
  <%= f.number_field :withdrawal %>
  <%= f.button :submit, "Submit", class: 'btn-success btn-block' %>
<% end %>